title = "DevSecOps Gitleaks Configuration"

[extend]
useDefault = true

[[rules]]
id = "hardcoded-password"
description = "Hardcoded password detected"
regex = '''(?i)(password|passwd|pwd|pass)\s*[:=]\s*["']?[A-Za-z0-9!@#$%^&*._-]{6,}["']?'''
keywords = [
    "password",
    "passwd",
    "pwd",
    "pass"
]

[rules.allowlist]
description = "Terraform references are not hardcoded secrets"

regexTarget = "line"

regexes = [
    '''(?i)\b(?:var\.[a-zA-Z0-9_.-]+|data\.azurerm_key_vault_secret\.[a-zA-Z0-9_.-]+\.value)\b'''
]
