name: DevSecOps Pipeline

on:
  push:
    branches:
      - feature

jobs:

  gitleaks:
    name: Secret Detection
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        run: |
          VERSION="8.30.1"

          curl -sSfL \
            "https://github.com/gitleaks/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_linux_x64.tar.gz" \
            -o gitleaks.tar.gz

          tar -xzf gitleaks.tar.gz gitleaks
          sudo mv gitleaks /usr/local/bin/gitleaks

          gitleaks version

      - name: Scan Repository
        run: |
          gitleaks git . \
            --config ./gitleaks.toml \
            --redact \
            --verbose


  semgrep:
    name: SAST - Semgrep
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: |
          python3 -m pip install semgrep

      - name: Run Semgrep
        run: |
          semgrep scan \
            --config p/owasp-top-ten \
            --error 

  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build Application
        working-directory: ./Java-Login-App
        run: |
          mvn clean package -DskipTests

      - name: Run Tests
        working-directory: ./Java-Login-App
        run: |
          mvn test

  trivy-dependency-scan:
    name: Trivy Dependency Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          exit-code: '1'
