name: DevSecOps Pipeline

on:
  push:
    branches:
      - feature

jobs:

  gitleaks:
    name: Secret Detection
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        run: |
          VERSION="8.30.1"

          curl -sSfL \
            "https://github.com/gitleaks/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_linux_x64.tar.gz" \
            -o gitleaks.tar.gz

          tar -xzf gitleaks.tar.gz gitleaks
          sudo mv gitleaks /usr/local/bin/gitleaks

          gitleaks version

      - name: Scan Repository
        run: |
          gitleaks git . \
            --config ./gitleaks.toml \
            --redact \
            --verbose

  semgrep:
    name: SAST - Semgrep
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: |
          python3 -m pip install semgrep

      - name: Run Semgrep
        run: |
          semgrep scan \
            --config p/owasp-top-ten \
            --error 

  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build Application
        working-directory: ./Java-Login-App
        run: |
          mvn clean package -DskipTests

      - name: Run Tests
        working-directory: ./Java-Login-App
        run: |
          mvn test

      - name: Upload WAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-login-app-war
          path: Java-Login-App/target/*.war    

  trivy-dependency-scan:
    name: Trivy Dependency Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          exit-code: '1'        

  docker-build:
    name: Docker Build
    needs: build
    runs-on: ubuntu-latest

    steps:  

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Download WAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: java-login-app-war
          path: Java-Login-App/target

      - name: Verify WAR File
        run: |
          ls -lh Java-Login-App/target

      - name: Build Docker Image
        run: |
          docker build \
            -t java-login-app:${{ github.sha }} \
            .
      - name: Save Docker Image
        run: |
          docker save \
            java-login-app:${{ github.sha }} \
            -o java-login-app.tar

      - name: Upload Docker Image
        uses: actions/upload-artifact@v4
        with:
          name: java-login-app-image
          path: java-login-app.tar      

  Trivy-Container-image-scan:
    name: Trivy Container Image Scan
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
    
      - name: Download Docker Image
        uses: actions/download-artifact@v4
        with:
          name: java-login-app-image

      - name: Verify Docker Image Artifact
        run: |
          ls -lh
          file java-login-app.tar    

      - name: Load Docker Image
        run: |
          docker load -i java-login-app.tar

      - name: Verify Docker Image
        run: |
          docker images    

      - name: Trivy Container Image Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'java-login-app:${{ github.sha }}'
          format: 'table'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          exit-code: '1'

  syft-sbom:
    name: Generate SBOM
    needs: docker-build
    runs-on: ubuntu-latest

    steps:

      - name: Download Docker Image
        uses: actions/download-artifact@v4
        with:
          name: java-login-app-image

      - name: Load Docker Image
        run: |
          docker load -i java-login-app.tar

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: 'java-login-app:${{ github.sha }}'
          format: cyclonedx-json
          output-file: sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: java-login-app-sbom
          path: sbom.json

  checkov:
    name: Checkov IaC Security Scan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          output_format: cli
          soft_fail: true                
